#!/usr/bin/perl -w

=head1 NAME

dh_auto_clean_nant - automatically cleans up after a nant build

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_auto_clean_nant> [S<I<debhelper options>>]

=head1 DESCRIPTION

dh_auto_clean_nant is a debhelper program that tries to automatically clean up
after a nant build.

=head1 OPTIONS

=over 4

=item B<--> I<params>

Pass "params" to the program that is run. These can be used to supplement
or override any standard parameters that dh_auto_build_nant passes.

=back

=cut

init();

doit("nant", "clean", @{$dh{U_PARAMS}});

=head1 SEE ALSO

L<debhelper(7)>

This program is a part of cli-common-dev.

=head1 AUTHOR

This program is partly based on dh_auto_clean developed by Joey Hess <joeyh@debian.org>

=cut
