#!/usr/bin/perl -w

=head1 NAME

dh_auto_build_nant - automatically builds a package that is based on nant

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_auto_build> [S<I<debhelper options>>] [S<B<--> I<params>>]

=head1 DESCRIPTION

dh_auto_build_nant is a debhelper program that tries to automatically
build a package that is based on ant.

=head1 OPTIONS

=over 4

=item B<--> I<params>

Pass "params" to the program that is run. These can be used to supplement
or override any standard parameters that dh_auto_build_nant passes.

=back

=cut

init();

doit("nant", @{$dh{U_PARAMS}});

=head1 SEE ALSO

L<debhelper(7)>

This program is a part of cli-common-dev.

=head1 AUTHOR

Mirco Bauer <meebey@debian.org>

This program is partly based on dh_auto_build developed by Joey Hess <joeyh@debian.org>

=cut
