#!/bin/bash

if [ ! -x /usr/lib/cli-common/runtimes.d/$1 ]; then
    echo E: Cannot remove GAC $1
    exit 1
fi

echo "Removing packages from $1"

for file in /usr/lib/cli-common/packages.d/*.installcligac
do
  if [ -f $file ]; then
      /usr/lib/cli-common/runtimes.d/$1 remove \
	  $(basename $file .installcligac)
  fi
done
