ildasm-monodis		/usr/share/cli-common/
cli.make		/usr/share/cli-common/
cli.pm			/usr/share/perl5/Debian/Debhelper/Sequence/
cli-nant.make		/usr/share/cli-common/
cli_nant.pm		/usr/share/perl5/Debian/Debhelper/Sequence/

dh_makeclilibs		/usr/bin/
dh_clideps		/usr/bin/
dh_clifixperms		/usr/bin/
dh_clistrip		/usr/bin/
dh_auto_build_nant	/usr/bin/
dh_auto_clean_nant	/usr/bin/

dh_installcligac	/usr/bin/
postinst-cligac		/usr/share/debhelper/autoscripts/
prerm-cligac		/usr/share/debhelper/autoscripts/

dh_installcliframework	/usr/bin/
postinst-cliframework	/usr/share/debhelper/autoscripts/
prerm-cliframework	/usr/share/debhelper/autoscripts/

dh_cligacpolicy		/usr/bin/
postinst-cligacpolicy	/usr/share/debhelper/autoscripts/
postrm-cligacpolicy     /usr/share/debhelper/autoscripts/

mono.pub		/usr/share/cli-common/keys/
mono.snk		/usr/share/cli-common/keys/
